### ISSUE TITLE
Class-10 .initIndexPage Method

### ISSUE THREAD

**Issue by apalm112** [MatthewAllanWilson/portfolio#21]
The .initIndexPage method in the view.js file needs to have to method calls below it, moved into it so those functions will be executed.

`projectView.initIndexPage = function () {`
    `Post.all.forEach(function(a){`
     `$('#projects').append(a.toHtml());`
    `});`
  `};`

  `projectView.handleMainNav();`
  `projectView.populateFilter();`
  `projectView.handleFilter();`

**Comment by MatthewAllanWilson** [comment]
Check!
